### ISSUE TITLE
Issue with conflicting instructions 

### ISSUE THREAD

**Issue by cochrancj** [cochrancj/P1_ConcentrationGame#1]
I am having issues with getting the background images for my cards to populate how and when I want them to and still play nice with card flipping and providing a mechanism for comparison.

**Comment by ajhofferber** [comment]
Hey! are you still having this issue?

**Comment by cochrancj** [comment]
I've given myself vapor lock with too many possible avenues to go down. I know _logically_ where I need to go and can explain it in English; but when I try and pick a freaking direction to go down with my code, I get hopelessly lost.
